// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_AfT5CtMULRlh8e-YtJ1sAC2CwtpfTJs',
    appId: '1:530636845251:web:0837a38e1e32e504623276',
    messagingSenderId: '530636845251',
    projectId: 'tamil-ebook-reader',
    authDomain: 'tamil-ebook-reader.firebaseapp.com',
    storageBucket: 'tamil-ebook-reader.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyHRTIqjuJvxqii09nkHmyWjOi4y-gHI',
    appId: '1:530636845251:android:3cc58c9aa1c3b132623276',
    messagingSenderId: '530636845251',
    projectId: 'tamil-ebook-reader',
    storageBucket: 'tamil-ebook-reader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzg0P1S0Z-wGhsp2LPwfa_-CBtBSqcxUw',
    appId: '1:530636845251:ios:ab6e2fddd10635d8623276',
    messagingSenderId: '530636845251',
    projectId: 'tamil-ebook-reader',
    storageBucket: 'tamil-ebook-reader.firebasestorage.app',
    iosBundleId: 'com.example.tamilEbookReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzg0P1S0Z-wGhsp2LPwfa_-CBtBSqcxUw',
    appId: '1:530636845251:ios:ab6e2fddd10635d8623276',
    messagingSenderId: '530636845251',
    projectId: 'tamil-ebook-reader',
    storageBucket: 'tamil-ebook-reader.firebasestorage.app',
    iosBundleId: 'com.example.tamilEbookReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_AfT5CtMULRlh8e-YtJ1sAC2CwtpfTJs',
    appId: '1:530636845251:web:96d02a8bb81ff891623276',
    messagingSenderId: '530636845251',
    projectId: 'tamil-ebook-reader',
    authDomain: 'tamil-ebook-reader.firebaseapp.com',
    storageBucket: 'tamil-ebook-reader.firebasestorage.app',
  );
}
